# Generated by Django 5.1.5 on 2025-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
